### ISSUE TITLE
TypeError: can only concatenate list (not "dict") to list

### ISSUE THREAD

**Issue by 875798590** [ibadr/RetinaFace#1]
请问这个如何解决?
PS D:\work\workspace\githubRGZN\RetinaFace_windows\rcnn\cython> python setup.py build_ext --inplace
Skipping GPU_NMS
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
building 'bbox' extension
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "C:\Program Files\Python27\lib\site-packages\setuptools\__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Program Files\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Program Files\Python27\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 118, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Program Files\Python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Program Files\Python27\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "C:\Program Files\Python27\lib\distutils\msvc9compiler.py", line 546, in compile
    extra_postargs)
TypeError: can only concatenate list (not "dict") to list
PS D:\work\workspace\githubRGZN\RetinaFace_windows\rcnn\cython>

**Comment by balabala7776** [comment]
请问解决了吗？我也遇到了
